server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600

      routes:

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - name: RoleFilter
              args:
                roles:
                  - PUBLIC

        - id: oauth2-authorization
          uri: lb://auth-service
          predicates:
            - Path=/oauth2/authorization/**
          filters:
            - name: RoleFilter
              args:
                roles:
                  - PUBLIC

        - id: oauth2-callback
          uri: lb://auth-service
          predicates:
            - Path=/login/oauth2/code/**
          filters:
            - name: RoleFilter
              args:
                roles:
                  - PUBLIC

        - id: user-service
          uri: lb://auth-service
          predicates:
            - Path=/api/user/**
          filters:
            - name: RoleFilter
              args:
                roles:
                  - DRIVER
                  - MANAGER
                  - ADMIN

        - id: vehicle-service
          uri: lb://vehicle-service
          predicates:
            - Path=/api/vehicle/**
          filters:
            - name: RoleFilter
              args:
                roles:
                  - DRIVER
                  - ADMIN

        - id: parkinglot-read
          uri: lb://parkinglot-service
          predicates:
            - Path=/api/parking-lots/**
            - Method=GET
          filters:
            - name: RoleFilter
              args:
                roles:
                  - DRIVER
                  - MANAGER
                  - ADMIN

        - id: parkinglot-write
          uri: lb://parkinglot-service
          predicates:
            - Path=/api/parking-lots/**
            - Method=POST,PUT,DELETE,PATCH
          filters:
            - name: RoleFilter
              args:
                roles:
                  - MANAGER
                  - ADMIN

        - id: parkingspot-read
          uri: lb://parkingspot-service
          predicates:
            - Path=/api/parking-spots/**
            - Method=GET
          filters:
            - name: RoleFilter
              args:
                roles:
                  - DRIVER
                  - MANAGER
                  - ADMIN

        - id: parkingspot-write
          uri: lb://parkingspot-service
          predicates:
            - Path=/api/parking-spots/**
            - Method=POST,PUT,DELETE,PATCH
          filters:
            - name: RoleFilter
              args:
                roles:
                  - MANAGER
                  - ADMIN
                  - DRIVER

        - id: booking-read
          uri: lb://booking-service
          predicates:
            - Path=/api/bookings/**
            - Method=GET
          filters:
            - name: RoleFilter
              args:
                roles:
                  - DRIVER
                  - MANAGER
                  - ADMIN

        - id: booking-write
          uri: lb://booking-service
          predicates:
            - Path=/api/bookings/**
            - Method=POST,PUT,DELETE
          filters:
            - name: RoleFilter
              args:
                roles:
                  - DRIVER
                  - ADMIN

        - id: payment-read
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**
            - Method=GET
          filters:
            - name: RoleFilter
              args:
                roles:
                  - DRIVER
                  - ADMIN

        - id: payment-write
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**
            - Method=POST,PUT,DELETE,PATCH
          filters:
            - name: RoleFilter
              args:
                roles:
                  - DRIVER
                  - ADMIN

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
          filters:
            - name: RoleFilter
              args:
                roles:
                  - DRIVER
                  - MANAGER
                  - ADMIN

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

security:
  jwt:
    secret: ${JWT_SECRET_KEY}