spring:
  application:
    name: notification-service

  datasource:
    url: ${DATABASE}
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8086

brevo:
  api-key: ${BREVO_API_KEY}        # same key as auth-service
  sender:
    email: ${BREVO_SENDER_MAIL}    # same sender as auth-service
    name: ${BREVO_SENDER_NAME}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}